
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilee
 */
public class HomeScreen extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
EmployeeDetails e;
AddNewJob a;
JobDetails j;
Attendance at;
PaySlip ps;
//EditDetails ed;
public static String user;
   
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        
        setUserId();
        initComponents();
        heading();
        e= new EmployeeDetails();
        a = new AddNewJob();
        j = new JobDetails();
        at = new Attendance();
        ps= new PaySlip();
        //ed= new EditDetails();
        
        DynamicPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(e,c);
        DynamicPanel.add(a, c);
        DynamicPanel.add(j, c);
        DynamicPanel.add(at, c);
        DynamicPanel.add(ps, c);
        //DynamicPanel.add(ed,c);
        
        e.setVisible(true);
        a.setVisible(false);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(false);
        //ed.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void heading()
    {
        LoginForm lg6 = new LoginForm();
        fn.setText(lg6.lastname);
        ln.setText(lg6.firstname);
        
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3_bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EmployeeDetails = new javax.swing.JPanel();
        EmployeeDetails_L = new javax.swing.JLabel();
        JobDetails = new javax.swing.JPanel();
        JobDetails_L = new javax.swing.JLabel();
        Attendance = new javax.swing.JPanel();
        Attendance_L = new javax.swing.JLabel();
        PaySlips = new javax.swing.JPanel();
        Payslip_L = new javax.swing.JLabel();
        AddNewJob = new javax.swing.JPanel();
        AddNewText_L = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("-");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel3_bg.setBackground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout jPanel3_bgLayout = new javax.swing.GroupLayout(jPanel3_bg);
        jPanel3_bg.setLayout(jPanel3_bgLayout);
        jPanel3_bgLayout.setHorizontalGroup(
            jPanel3_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3_bgLayout.setVerticalGroup(
            jPanel3_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeDetails.setBackground(new java.awt.Color(36, 47, 65));
        EmployeeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeDetailsMousePressed(evt);
            }
        });

        EmployeeDetails_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmployeeDetails_L.setForeground(new java.awt.Color(204, 204, 204));
        EmployeeDetails_L.setText("                     Employee Details");
        EmployeeDetails_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeDetails_LMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeDetails_LMousePressed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeDetailsLayout = new javax.swing.GroupLayout(EmployeeDetails);
        EmployeeDetails.setLayout(EmployeeDetailsLayout);
        EmployeeDetailsLayout.setHorizontalGroup(
            EmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeDetails_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        EmployeeDetailsLayout.setVerticalGroup(
            EmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeDetails_L, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jPanel2.add(EmployeeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 378, -1));

        JobDetails.setBackground(new java.awt.Color(255, 255, 255));
        JobDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JobDetailsMousePressed(evt);
            }
        });

        JobDetails_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JobDetails_L.setText("                         Job Details");
        JobDetails_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobDetails_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JobDetailsLayout = new javax.swing.GroupLayout(JobDetails);
        JobDetails.setLayout(JobDetailsLayout);
        JobDetailsLayout.setHorizontalGroup(
            JobDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JobDetails_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        JobDetailsLayout.setVerticalGroup(
            JobDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JobDetails_L, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel2.add(JobDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 441, 378, -1));

        Attendance.setBackground(new java.awt.Color(255, 255, 255));
        Attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AttendanceMousePressed(evt);
            }
        });

        Attendance_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Attendance_L.setText("                        Time Sheet");
        Attendance_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Attendance_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AttendanceLayout = new javax.swing.GroupLayout(Attendance);
        Attendance.setLayout(AttendanceLayout);
        AttendanceLayout.setHorizontalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Attendance_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        AttendanceLayout.setVerticalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Attendance_L, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel2.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 528, 378, -1));

        PaySlips.setBackground(new java.awt.Color(255, 255, 255));
        PaySlips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaySlipsMousePressed(evt);
            }
        });

        Payslip_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Payslip_L.setText("                           PaySlip's");
        Payslip_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Payslip_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PaySlipsLayout = new javax.swing.GroupLayout(PaySlips);
        PaySlips.setLayout(PaySlipsLayout);
        PaySlipsLayout.setHorizontalGroup(
            PaySlipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Payslip_L, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        PaySlipsLayout.setVerticalGroup(
            PaySlipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Payslip_L, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel2.add(PaySlips, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 615, 378, -1));

        AddNewJob.setBackground(new java.awt.Color(255, 255, 255));
        AddNewJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddNewJobMousePressed(evt);
            }
        });

        AddNewText_L.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddNewText_L.setText("                       Add New Job");
        AddNewText_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewText_LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddNewJobLayout = new javax.swing.GroupLayout(AddNewJob);
        AddNewJob.setLayout(AddNewJobLayout);
        AddNewJobLayout.setHorizontalGroup(
            AddNewJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewText_L, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        AddNewJobLayout.setVerticalGroup(
            AddNewJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewText_L, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jPanel2.add(AddNewJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 353, 378, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payroll");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 79, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Management");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 109, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 139, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 153, 51));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Logout");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Hello, ");

        fn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fn.setText("jLabel8");

        ln.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ln.setText("jLabel9");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1023, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(fn)
                    .addComponent(ln))
                .addContainerGap())
        );

        DynamicPanel.setBackground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 764, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1748, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setJobDetailsPane()
    {
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        setColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
        
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(true);
        at.setVisible(false);
        ps.setVisible(false);
    }
    
    private void EmployeeDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDetailsMousePressed
        setColor(EmployeeDetails);
        resetColor(AddNewJob);
        resetColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
        a.setVisible(false);
        e.setVisible(true);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(false);
        
        
        
        
        
    }//GEN-LAST:event_EmployeeDetailsMousePressed

    private void JobDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobDetailsMousePressed
        
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        setColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
        
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(true);
        at.setVisible(false);
        ps.setVisible(false);
        
    }//GEN-LAST:event_JobDetailsMousePressed

    private void AttendanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendanceMousePressed
        
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        
        resetColor(JobDetails);
        setColor(Attendance);
        resetColor(PaySlips);
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(true);
        ps.setVisible(false);
        
    }//GEN-LAST:event_AttendanceMousePressed

    private void PaySlipsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaySlipsMousePressed
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        
        resetColor(JobDetails);
        resetColor(Attendance);
        setColor(PaySlips);
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(true);
    }//GEN-LAST:event_PaySlipsMousePressed

    private void AddNewJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewJobMousePressed
        setColor(AddNewJob);
        resetColor(EmployeeDetails);
        
        resetColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
        a.setVisible(true);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(false);
    }//GEN-LAST:event_AddNewJobMousePressed

    private void EmployeeDetails_LMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDetails_LMousePressed
       
    }//GEN-LAST:event_EmployeeDetails_LMousePressed

    private void EmployeeDetails_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeDetails_LMouseClicked
        setColor(EmployeeDetails);
        resetColor(AddNewJob);
        resetColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
       
        setColor(EmployeeDetails_L);
        resetColor(AddNewText_L);
        resetColor(JobDetails_L);
        resetColor(Attendance_L);
        resetColor(Payslip_L);
        
        a.setVisible(false);
        e.setVisible(true);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(false);
        
    }//GEN-LAST:event_EmployeeDetails_LMouseClicked

    private void AddNewText_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewText_LMouseClicked
        setColor(AddNewJob);
        resetColor(EmployeeDetails);
        resetColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
       
        setColor(AddNewText_L);
        resetColor(EmployeeDetails_L);
        resetColor(JobDetails_L);
        resetColor(Attendance_L);
        resetColor(Payslip_L);
       
        a.setVisible(true);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(false);
    }//GEN-LAST:event_AddNewText_LMouseClicked

    private void JobDetails_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobDetails_LMouseClicked
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        setColor(JobDetails);
        resetColor(Attendance);
        resetColor(PaySlips);
        
        setColor(JobDetails_L);
        resetColor(EmployeeDetails_L);
        resetColor(AddNewText_L);
        resetColor(Attendance_L);
        resetColor(Payslip_L);
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(true);
        at.setVisible(false);
        ps.setVisible(false);
    }//GEN-LAST:event_JobDetails_LMouseClicked

    private void Attendance_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Attendance_LMouseClicked
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);
        resetColor(JobDetails);
        setColor(Attendance);
        resetColor(PaySlips);
     
        setColor(Attendance_L);
        resetColor(EmployeeDetails_L);
        resetColor(AddNewText_L);
        resetColor(JobDetails_L);
        
        resetColor(Payslip_L);
        
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(true);
        ps.setVisible(false);
    }//GEN-LAST:event_Attendance_LMouseClicked

    private void Payslip_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payslip_LMouseClicked
        resetColor(AddNewJob);
        resetColor(EmployeeDetails);  
        resetColor(JobDetails);
        resetColor(Attendance);
        setColor(PaySlips);
      
        setColor(Payslip_L);
        resetColor(EmployeeDetails_L);
        resetColor(AddNewText_L);
        resetColor(JobDetails_L);
        resetColor(Attendance_L);
    
        a.setVisible(false);
        e.setVisible(false);
        j.setVisible(false);
        at.setVisible(false);
        ps.setVisible(true);
    }//GEN-LAST:event_Payslip_LMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        LoginForm l6 = new LoginForm();
        this.dispose();
        l6.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    
    
    
    void setColor(JLabel label)
    {
        label.setBackground(new Color(36,47,65));
        label.setForeground(new Color(204,204,204));
    }
    
    void resetColor(JLabel label)
    {
        label.setBackground(new Color(255,255,255));
        label.setForeground(new Color(0,0,0));
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(36,47,65));
        //label.setForeground(new Color(204,204,204));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(255,255,255));
        //label.setForeground(new Color(204,204,204));

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNewJob;
    private javax.swing.JLabel AddNewText_L;
    private javax.swing.JPanel Attendance;
    private javax.swing.JLabel Attendance_L;
    public static javax.swing.JPanel DynamicPanel;
    public javax.swing.JPanel EmployeeDetails;
    public javax.swing.JLabel EmployeeDetails_L;
    private javax.swing.JPanel JobDetails;
    private javax.swing.JLabel JobDetails_L;
    private javax.swing.JPanel PaySlips;
    private javax.swing.JLabel Payslip_L;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3_bg;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel ln;
    // End of variables declaration//GEN-END:variables

    public void setUserId() {
         user = LoginForm.jTextFieldUsername.getText();
    }
}
